# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- refs/tags/*

pool:
  vmImage: windows-latest
 
steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Install-Module InvokeBuild -Force
        Install-Module PowerShellGet -Force
        Install-Module ModuleBuilder -Force
        Install-Module Pester -Force
        
        Invoke-Build
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'bin'
      ArtifactName: 'Microsoft365ServiceStatus-Module'
      publishLocation: 'Container'